import { Router } from "express";
import { listBooks, getBook, createBook, updateBook, deleteBook } from "../controllers/book.controller.js";
import { verifyJWT } from "../middleware/auth.js";
import { requireRole } from "../middleware/roles.js";
const r = Router();
r.get("/", listBooks);
r.get("/:id", getBook);
r.post("/", verifyJWT, requireRole("admin"), createBook);
r.put("/:id", verifyJWT, requireRole("admin"), updateBook);
r.delete("/:id", verifyJWT, requireRole("admin"), deleteBook);
export default r;
